backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: 'BlDataog'
    format: 'json'
    folder: 'assets/content/data'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'id', name: 'id', widget: 'number' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Restaurant name', name: 'restaurant', widget: 'string' }
      - { label: 'Phone number', name: 'phoneNumber', widget: 'string' }
      - { label: 'Website', name: 'website', widget: 'string' }
      - { label: 'Cuisine', name: 'cuisine', widget: 'markdown' }
      - { label: 'Additional info', name: 'additionalInfo', widget: 'markdown' }
      - { label: 'Image', name: 'image', widget: 'image', required: false, media_library: { config: {multiple: false } } }
- name: "spa"
  label: "SpaBlog"
  format: 'json'
  folder: 'assets/content/spa'
  create: true
  slug: '{{slug}}'
  editor:
    preview: false
  fields:
    - { label: 'id', name: 'id', widget: 'number' }
    - { label: 'Title', name: 'title', widget: 'string' }
    - { label: 'Content', name: 'content', widget: 'list' }
    - { label: 'Image', name: 'image', widget: 'image', required: false, media_library: { config: {multiple: false } } }
